ALTER TABLE `wallet_trade`
	ADD COLUMN `trade_packet` char(1)  COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'N' COMMENT '是否红包' after `trade_type` ,
	CHANGE `trade_amount` `trade_amount` decimal(8,2)   NULL DEFAULT 0.00 COMMENT '交易金额' after `trade_packet` ,
	CHANGE `trade_count` `trade_count` int(8)   NULL DEFAULT 1 COMMENT '交易数量' after `trade_amount` ,
	CHANGE `trade_remark` `trade_remark` varchar(200)  COLLATE utf8mb4_general_ci NULL COMMENT '交易备注' after `trade_count` ,
	CHANGE `trade_balance` `trade_balance` decimal(65,2)   NULL DEFAULT 0.00 COMMENT '余额' after `trade_remark` ,
	CHANGE `trade_status` `trade_status` char(1)  COLLATE utf8mb4_general_ci NULL COMMENT '交易状态' after `trade_balance` ,
	CHANGE `source_id` `source_id` bigint(20)   NULL DEFAULT 0 COMMENT '交易来源' after `trade_status` ,
	CHANGE `source_type` `source_type` varchar(4)  COLLATE utf8mb4_general_ci NULL COMMENT '交易来源' after `source_id` ,
	CHANGE `user_id` `user_id` bigint(20)   NULL DEFAULT 0 COMMENT '用户id' after `source_type` ,
	CHANGE `user_no` `user_no` varchar(32)  COLLATE utf8mb4_general_ci NULL COMMENT '用户号码' after `user_id` ,
	CHANGE `nickname` `nickname` varchar(20)  COLLATE utf8mb4_general_ci NULL COMMENT '用户昵称' after `user_no` ,
	CHANGE `phone` `phone` varchar(50)  COLLATE utf8mb4_general_ci NULL COMMENT '用户手机' after `nickname` ,
	CHANGE `portrait` `portrait` longtext  COLLATE utf8mb4_general_ci NULL COMMENT '用户头像' after `phone` ,
	CHANGE `group_id` `group_id` bigint(20)   NULL DEFAULT 0 COMMENT '群组' after `portrait` ,
	CHANGE `group_no` `group_no` varchar(32)  COLLATE utf8mb4_general_ci NULL COMMENT '群号' after `group_id` ,
	CHANGE `group_name` `group_name` varchar(50)  COLLATE utf8mb4_general_ci NULL COMMENT '群名' after `group_no` ,
	CHANGE `receive_id` `receive_id` bigint(20)   NULL DEFAULT 0 COMMENT '接收id' after `group_name` ,
	CHANGE `receive_no` `receive_no` varchar(32)  COLLATE utf8mb4_general_ci NULL COMMENT '接收号码' after `receive_id` ,
	CHANGE `receive_name` `receive_name` varchar(20)  COLLATE utf8mb4_general_ci NULL COMMENT '接收昵称' after `receive_no` ,
	CHANGE `receive_phone` `receive_phone` varchar(50)  COLLATE utf8mb4_general_ci NULL COMMENT '接收手机' after `receive_name` ,
	CHANGE `receive_portrait` `receive_portrait` longtext  COLLATE utf8mb4_general_ci NULL COMMENT '接收头像' after `receive_phone` ,
	CHANGE `create_time` `create_time` datetime   NULL COMMENT '生成时间' after `receive_portrait` ,
	CHANGE `update_time` `update_time` datetime   NULL COMMENT '更新时间' after `create_time` ,
	CHANGE `deleted` `deleted` tinyint(1)   NULL DEFAULT 0 COMMENT '注销0正常null注销' after `update_time` ,
	ADD KEY `trade_packet`(`trade_packet`) ;