ALTER TABLE `chat_user`
	ADD COLUMN `email` varchar(200)  COLLATE utf8mb4_general_ci NULL COMMENT '邮箱' after `phone` , 
	CHANGE `nickname` `nickname` varchar(32)  COLLATE utf8mb4_general_ci NULL COMMENT '昵称' after `email` , 
	CHANGE `portrait` `portrait` longtext  COLLATE utf8mb4_general_ci NULL COMMENT '头像' after `nickname` , 
	CHANGE `remark` `remark` varchar(2000)  COLLATE utf8mb4_general_ci NULL COMMENT '备注' after `portrait` , 
	CHANGE `gender` `gender` varchar(1)  COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '性别1男2女' after `remark` , 
	CHANGE `birthday` `birthday` date   NULL COMMENT '生日' after `gender` , 
	CHANGE `intro` `intro` varchar(200)  COLLATE utf8mb4_general_ci NULL COMMENT '介绍' after `birthday` , 
	CHANGE `province` `province` varchar(20)  COLLATE utf8mb4_general_ci NULL COMMENT '省份' after `intro` , 
	CHANGE `city` `city` varchar(20)  COLLATE utf8mb4_general_ci NULL COMMENT '城市' after `province` , 
	CHANGE `salt` `salt` varchar(4)  COLLATE utf8mb4_general_ci NULL COMMENT '盐' after `city` , 
	CHANGE `password` `password` varchar(32)  COLLATE utf8mb4_general_ci NULL COMMENT '密码' after `salt` , 
	CHANGE `pass` `pass` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'N' COMMENT '密码标志' after `password` , 
	CHANGE `auth` `auth` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '认证状态' after `pass` , 
	CHANGE `banned` `banned` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'N' COMMENT '封禁状态' after `auth` , 
	CHANGE `special` `special` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'N' COMMENT '测试账号' after `banned` , 
	CHANGE `abnormal` `abnormal` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'N' COMMENT '异常账号' after `special` , 
	CHANGE `payment` `payment` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'N' COMMENT '支付密码' after `abnormal` , 
	CHANGE `privacy_no` `privacy_no` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'Y' COMMENT '隐私no' after `payment` , 
	CHANGE `privacy_phone` `privacy_phone` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'Y' COMMENT '隐私手机' after `privacy_no` , 
	CHANGE `privacy_scan` `privacy_scan` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'Y' COMMENT '隐私扫码' after `privacy_phone` , 
	CHANGE `privacy_card` `privacy_card` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'Y' COMMENT '隐私名片' after `privacy_scan` , 
	CHANGE `privacy_group` `privacy_group` char(1)  COLLATE utf8mb4_general_ci NULL DEFAULT 'Y' COMMENT '隐私群组' after `privacy_card` , 
	CHANGE `login_ios` `login_ios` varchar(64)  COLLATE utf8mb4_general_ci NULL COMMENT '苹果openId' after `privacy_group` , 
	CHANGE `login_qq` `login_qq` varchar(64)  COLLATE utf8mb4_general_ci NULL COMMENT '球球openId' after `login_ios` , 
	CHANGE `login_wx` `login_wx` varchar(64)  COLLATE utf8mb4_general_ci NULL COMMENT '微信openId' after `login_qq` , 
	CHANGE `on_line` `on_line` datetime   NULL COMMENT '在线时间' after `login_wx` , 
	CHANGE `create_time` `create_time` datetime   NULL COMMENT '注册时间' after `on_line` , 
	CHANGE `ip` `ip` varchar(128)  COLLATE utf8mb4_general_ci NULL COMMENT 'IP地址' after `create_time` , 
	CHANGE `ip_addr` `ip_addr` varchar(128)  COLLATE utf8mb4_general_ci NULL COMMENT 'IP地址' after `ip` , 
	CHANGE `deleted` `deleted` tinyint(1)   NULL DEFAULT 0 COMMENT '注销0正常null注销' after `ip_addr` ;
