CREATE TABLE `chat_user` (
  `user_id` bigint(20) NOT NULL COMMENT '主键',
  `user_no` varchar(32) DEFAULT NULL COMMENT '聊天号码',
  `phone` varchar(50) DEFAULT NULL COMMENT '手机号',
  `nickname` varchar(32) DEFAULT NULL COMMENT '昵称',
  `portrait` longtext COMMENT '头像',
  `gender` varchar(1) DEFAULT '1' COMMENT '性别1男2女',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `intro` varchar(200) DEFAULT NULL COMMENT '介绍',
  `province` varchar(20) DEFAULT NULL COMMENT '省份',
  `city` varchar(20) DEFAULT NULL COMMENT '城市',
  `salt` varchar(4) DEFAULT NULL COMMENT '盐',
  `password` varchar(32) DEFAULT NULL COMMENT '密码',
  `pass` char(1) DEFAULT 'N' COMMENT '密码标志',
  `auth` char(1) DEFAULT '1' COMMENT '认证状态',
  `banned` char(1) DEFAULT 'N' COMMENT '封禁状态',
  `special` char(1) DEFAULT 'N' COMMENT '测试账号',
  `abnormal` char(1) DEFAULT 'N' COMMENT '异常账号',
  `payment` char(1) DEFAULT 'N' COMMENT '支付密码',
  `privacy_no` char(1) DEFAULT 'Y' COMMENT '隐私no',
  `privacy_phone` char(1) DEFAULT 'Y' COMMENT '隐私手机',
  `privacy_scan` char(1) DEFAULT 'Y' COMMENT '隐私扫码',
  `privacy_card` char(1) DEFAULT 'Y' COMMENT '隐私名片',
  `privacy_group` char(1) DEFAULT 'Y' COMMENT '隐私群组',
  `login_ios` varchar(64) DEFAULT NULL COMMENT '苹果openId',
  `login_qq` varchar(64) DEFAULT NULL COMMENT '球球openId',
  `login_wx` varchar(64) DEFAULT NULL COMMENT '微信openId',
  `on_line` datetime DEFAULT NULL COMMENT '在线时间',
  `create_time` datetime DEFAULT NULL COMMENT '注册时间',
  `ip` varchar(128) DEFAULT NULL COMMENT 'IP地址',
  `ip_addr` varchar(128) DEFAULT NULL COMMENT 'IP地址',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '注销0正常null注销',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `phone` (`phone`,`deleted`),
  UNIQUE KEY `chat_no` (`user_no`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天用户';