spring:
  profiles:
    active: dev

# 过滤器配置
filter:
  # 版本配置
  version:
    # 版本开关
    enabled: Y
    # 最低版本
    lowest: 1.0.0
  # 设备过滤
  device:
    # 设备开关
    enabled: Y
  # 过滤拦截
  exclude:
    # 过滤请求
    dataList:
      - /
      - /favicon.ico
      - /common/upgrade
      - /wallet/recharge/notifyAli
      - /wallet/recharge/notifyWx
      - /test/**
  # 签名过滤
  sign:
    # 签名开关
    enabled: Y
    # 移除前缀，比如/webApi
    prefix: "_"
    # appId
    appId: 2024
    # 私钥
    secret: 3e9f44aa8eaef18e
  # 免登录
  auth:
    # 过滤请求
    dataList:
      - /auth/sendCode
      - /auth/loginByPwd
      - /auth/loginByCode
      - /auth/register
      - /auth/forget
      - /auth/getQrCode
      - /wallet/recharge/notifyAli
      - /wallet/recharge/notifyWx
      - /common/upgrade
      - /error/**
      - /test/**
  # 禁用拦截
  banned:
    # 过滤请求
    dataList:
      - /auth/logout
      - /mine/getInfo
      - /banned/getInfo
      - /banned/appeal
      - /common/getUploadToken/**
  # xss过滤
  xss:
    # 过滤开关
    enabled: Y
    # 过滤请求
    dataList:
      - /mine/editPortrait
      - /mine/editAuth
      - /banned/apply
      - /group/manager/editPortrait
      - /collect/add
      - /emote/add
      - /inform/user
      - /inform/group
      - /common/feedback
      - /friend/moments
  # 地址转换
  path:
    # 前缀，默认/webApi
    prefix: "/webApi"
    # 映射map
    dataList:
      "ofyndizx9od5hgo0": "/auth/loginByPwd"
      "ofyndizx9od5hgo1": "/mine/getInfo"

# MyBatis配置
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.platform
  typeEnumsPackage: com.platform
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true
    #日志打印
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: true
  global-config:
    banner: false
    dbConfig:
      #逻辑删除
      logicDeleteValue: "null" # 逻辑已删除值(默认为 1)
      logicNotDeleteValue: 0 # 逻辑未删除值(默认为 0)

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  # 合理化分页
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    com.platform: info
    org.springframework: warn
    org.apache.rocketmq: error