CREATE TABLE `chat_group_member` (
  `member_id` bigint(20) NOT NULL COMMENT '主键',
  `group_id` bigint(20) DEFAULT NULL COMMENT '群组id',
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户id',
  `user_no` varchar(32) DEFAULT NULL COMMENT '聊天号码',
  `nickname` varchar(20) DEFAULT NULL COMMENT '备注',
  `portrait` longtext COMMENT '头像',
  `remark` varchar(20) DEFAULT NULL COMMENT '备注',
  `member_type` varchar(10) DEFAULT 'normal' COMMENT '成员类型',
  `top` char(1) DEFAULT 'N' COMMENT '是否置顶',
  `disturb` char(1) DEFAULT 'N' COMMENT '是否免打扰',
  `member_source` char(1) DEFAULT '1' COMMENT '进群来源',
  `packet_white` char(1) DEFAULT 'N' COMMENT '禁抢白名单',
  `speak` char(1) DEFAULT 'N' COMMENT '禁言开关',
  `speak_time` datetime DEFAULT NULL COMMENT '禁言时间',
  `create_time` datetime DEFAULT NULL COMMENT '加入时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '注销0正常null注销',
  PRIMARY KEY (`member_id`),
  UNIQUE KEY `idx_group` (`user_id`,`group_id`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='群组成员';
