CREATE TABLE `chat_group` (
  `group_id` bigint(20) NOT NULL COMMENT '主键',
  `group_name` varchar(50) DEFAULT NULL COMMENT '群名',
  `group_no` varchar(32) DEFAULT NULL COMMENT '群号',
  `banned` char(1) DEFAULT 'N' COMMENT '封禁群组',
  `portrait` longtext COMMENT '群组头像',
  `notice` varchar(200) DEFAULT NULL COMMENT '通知公告',
  `notice_top` char(1) DEFAULT 'N' COMMENT '悬浮开关',
  `config_member` char(1) DEFAULT 'N' COMMENT '成员保护',
  `config_invite` char(1) DEFAULT 'Y' COMMENT '允许邀请',
  `config_speak` char(1) DEFAULT 'N' COMMENT '全员禁言',
  `config_title` char(1) DEFAULT 'Y' COMMENT '群组头衔',
  `config_audit` char(1) DEFAULT 'N' COMMENT '群组审核',
  `config_media` char(1) DEFAULT 'Y' COMMENT '发送资源',
  `config_assign` char(1) DEFAULT 'N' COMMENT '专属可见',
  `config_nickname` char(1) DEFAULT 'Y' COMMENT '昵称开关',
  `config_packet` char(1) DEFAULT 'Y' COMMENT '红包开关',
  `config_amount` char(1) DEFAULT 'Y' COMMENT '金额开关',
  `config_scan` char(1) DEFAULT 'Y' COMMENT '二维码',
  `config_receive` char(1) DEFAULT 'N' COMMENT '红包禁抢',
  `group_level` int(4) DEFAULT '0' COMMENT '群组等级',
  `group_level_count` int(4) DEFAULT '0' COMMENT '群组等级容量',
  `group_level_price` decimal(8,2) DEFAULT '0.00' COMMENT '群组等级价格',
  `group_level_time` datetime DEFAULT NULL COMMENT '群组容量时间',
  `privacy_no` char(1) DEFAULT 'Y' COMMENT '隐私开关',
  `privacy_scan` char(1) DEFAULT 'Y' COMMENT '隐私开关',
  `privacy_name` char(1) DEFAULT 'Y' COMMENT '隐私开关',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '注销0正常null注销',
  PRIMARY KEY (`group_id`),
  UNIQUE KEY `group_no` (`group_no`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天群组';